matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk7
      android:
        components:
          - android-28
      before_install:
         - whatever
    - language: objective-c
      os: osx
      osx_image: xcode7.3
      before_install:
         - carthage update